#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : system_top.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Feb 07 11:33:15 CST 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: system_top.sh [-help]
# usage: system_top.sh [-lib_map_path]
# usage: system_top.sh [-noclean_files]
# usage: system_top.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system_top.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_24 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system_top.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../bd/system_top/ip/system_top_xbar_0/sim/system_top_xbar_0.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_clk_wiz_0_0_1/system_top_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_clk_wiz_0_0_1/system_top_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system_top/ip/system_top_proc_sys_reset_1_0/sim/system_top_proc_sys_reset_1_0.vhd" \
    "$ref_dir/../../../bd/system_top/ip/system_top_proc_sys_reset_0_0_1/sim/system_top_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../bd/system_top/ip/system_top_util_vector_logic_0_0_1/sim/system_top_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/system_top_mig_7series_0_1_mig_sim.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1/user_design/rtl/system_top_mig_7series_0_1.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_util_vector_logic_1_0/sim/system_top_util_vector_logic_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system_top/ip/system_top_axi_gpio_0_0/sim/system_top_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/system_top/ip/system_top_rst_clk_wiz_0_200M_0/sim/system_top_rst_clk_wiz_0_200M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/adv_timer_apb_if.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/apb_adv_timer.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_gpio/apb_gpio.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c/apb_i2c.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/apb_spi_master.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_uart/apb_uart.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/comparator.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_biu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_clk_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_clkgate.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_core.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_cpu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_cpu_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_dtcm_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_dtcm_ram.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu_bjp.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu_csrctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu_dpath.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu_lsuagu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu_muldiv.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_alu_rglr.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_branchslv.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_commit.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_csr.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_decode.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_disp.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_excp.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_longpwbck.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_nice.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_oitf.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_regfile.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_exu_wbck.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_ifu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_ifu_ifetch.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_ifu_ift2icb.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_ifu_litebpu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_ifu_minidec.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_irq_sync.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_itcm_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_itcm_ram.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_lsu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_lsu_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_reset_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/soc/e203_soc_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/core/e203_srams.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_clint.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_gfcm.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_hclkgen.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_hclkgen_rstsync.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_main.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_mems.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_nice_core.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_perips.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_plic.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_pll.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_pllclkdiv.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/subsys/e203_subsys_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c/i2c_master_bit_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c/i2c_master_byte_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/input_stage.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_uart/io_generic_fifo.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/prescaler.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_1cyc_sram_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_AsyncResetReg.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_AsyncResetRegVec.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_AsyncResetRegVec_1.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_AsyncResetRegVec_129.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_AsyncResetRegVec_36.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_DeglitchShiftRegister.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_LevelGateway.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_ResetCatchAndSync.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_ResetCatchAndSync_2.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_aon.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_aon_lclkgen_regs.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_aon_porrst.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_aon_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_aon_wrapper.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_clint.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_clint_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/debug/sirv_debug_csr.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/debug/sirv_debug_module.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/debug/sirv_debug_ram.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/debug/sirv_debug_rom.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_expl_axi_slv.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_flash_qspi.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_flash_qspi_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_gnrl_bufs.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_gnrl_dffs.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_gnrl_icbs.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_gnrl_ram.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_hclkgen_regs.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/fab/sirv_icb1to16_bus.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/fab/sirv_icb1to2_bus.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/fab/sirv_icb1to8_bus.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/debug/sirv_jtag_dtm.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_jtaggpioport.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/mems/sirv_mrom.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/mems/sirv_mrom_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_plic_man.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_plic_top.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_pmu.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_pmu_core.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_qspi_arbiter.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_qspi_fifo.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_qspi_media.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_qspi_physical.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_queue.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_queue_1.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_repeater_6.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_rtc.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_sim_ram.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_spi_flashmap.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/general/sirv_sram_icb_ctrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_tl_repeater_5.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_tlfragmenter_qspi_1.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_tlwidthwidget_qspi.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/sirv_wdog.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/spi_master_apb_if.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/spi_master_clkgen.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/spi_master_controller.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/spi_master_fifo.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/spi_master_rx.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_spi_master/spi_master_tx.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/timer_cntrl.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/timer_module.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_uart/uart_interrupt.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_uart/uart_rx.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_uart/uart_tx.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_adv_timer/up_down_counter.v" \
    "$ref_dir/../../../bd/system_top/ipshared/a474/system.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_system_e203_0_0_1/sim/system_top_system_e203_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../bd/system_top/ip/system_top_auto_pc_1/sim/system_top_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/d0f7" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../bd/system_top/ipshared/a474/core" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/perips/apb_i2c" +incdir+"$ref_dir/../../../../sys_top_bd.gen/sources_1/bd/system_top/ipshared/a474/core" \
    "$ref_dir/../../../bd/system_top/ip/system_top_auto_cc_0_1/sim/system_top_auto_cc_0.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_auto_cc_1/sim/system_top_auto_cc_1.v" \
    "$ref_dir/../../../bd/system_top/ip/system_top_auto_pc_0_1/sim/system_top_auto_pc_0.v" \
    "$ref_dir/../../../bd/system_top/sim/system_top.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system_top xil_defaultlib.glbl -o system_top_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_top_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system_top.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_top_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_top_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system_top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system_top.sh [-help]\n\
Usage: system_top.sh [-lib_map_path]\n\
Usage: system_top.sh [-reset_run]\n\
Usage: system_top.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
