# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.srcs/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1.xci
# IP: The module: 'system_top_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.srcs/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1.xci
# IP: The module: 'system_top_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
