# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.srcs/sources_1/bd/system_top/ip/system_top_system_ila_0_1/system_top_system_ila_0_1.xci
# IP: The module: 'system_top_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/bd_bcc6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bcc6 || ORIG_REF_NAME==bd_bcc6} -quiet] -quiet

# IP: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/bd_bcc6_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bcc6_ila_lib_0 || ORIG_REF_NAME==bd_bcc6_ila_lib_0} -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bcc6_ila_lib_0 || ORIG_REF_NAME==bd_bcc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bcc6_ila_lib_0 || ORIG_REF_NAME==bd_bcc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/bd_bcc6_ila_lib_0_ooc.xdc

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/bd_bcc6_ooc.xdc

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/system_top_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.srcs/sources_1/bd/system_top/ip/system_top_system_ila_0_1/system_top_system_ila_0_1.xci
# IP: The module: 'system_top_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/bd_bcc6.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bcc6 || ORIG_REF_NAME==bd_bcc6} -quiet] -quiet

# IP: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/bd_bcc6_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bcc6_ila_lib_0 || ORIG_REF_NAME==bd_bcc6_ila_lib_0} -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bcc6_ila_lib_0 || ORIG_REF_NAME==bd_bcc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bcc6_ila_lib_0 || ORIG_REF_NAME==bd_bcc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/ip/ip_0/bd_bcc6_ila_lib_0_ooc.xdc

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/bd_0/bd_bcc6_ooc.xdc

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/ip/system_top_system_ila_0_1/system_top_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
