# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/oppenyes/workspace/my_git/e203_zs/constrs/nuclei-master.xdc

# Block Designs: bd/system_top/system_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top || ORIG_REF_NAME==system_top} -quiet] -quiet

# IP: bd/system_top/ip/system_top_xbar_0/system_top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_xbar_0 || ORIG_REF_NAME==system_top_xbar_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_axi_interconnect_0_0_1/system_top_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_axi_interconnect_0_0 || ORIG_REF_NAME==system_top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_clk_wiz_0_0_1/system_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_clk_wiz_0_0 || ORIG_REF_NAME==system_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_proc_sys_reset_1_0/system_top_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_proc_sys_reset_1_0 || ORIG_REF_NAME==system_top_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_proc_sys_reset_0_0_1/system_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_proc_sys_reset_0_0 || ORIG_REF_NAME==system_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_util_vector_logic_0_0_1/system_top_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_util_vector_logic_0_0 || ORIG_REF_NAME==system_top_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_mig_7series_0_1_1/system_top_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_mig_7series_0_1 || ORIG_REF_NAME==system_top_mig_7series_0_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_util_vector_logic_1_0/system_top_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_util_vector_logic_1_0 || ORIG_REF_NAME==system_top_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_axi_gpio_0_0/system_top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_axi_gpio_0_0 || ORIG_REF_NAME==system_top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_system_e203_0_0_1/system_top_system_e203_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_system_e203_0_0 || ORIG_REF_NAME==system_top_system_e203_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_axi_gpio_0_1/system_top_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_axi_gpio_0_1 || ORIG_REF_NAME==system_top_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_system_ila_0_1/system_top_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_system_ila_0_1 || ORIG_REF_NAME==system_top_system_ila_0_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_auto_pc_2/system_top_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_auto_pc_2 || ORIG_REF_NAME==system_top_auto_pc_2} -quiet] -quiet

# IP: bd/system_top/ip/system_top_auto_cc_0_1/system_top_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_auto_cc_0 || ORIG_REF_NAME==system_top_auto_cc_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_auto_pc_0_1/system_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_auto_pc_0 || ORIG_REF_NAME==system_top_auto_pc_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_auto_pc_1/system_top_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_auto_pc_1 || ORIG_REF_NAME==system_top_auto_pc_1} -quiet] -quiet

# XDC: /home/oppenyes/workspace/my_git/e203_zs/prj/sys_top_bd/sys_top_bd.gen/sources_1/bd/system_top/system_top_ooc.xdc
